version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: yarn run start:dev
        ports:
            - 4000:4000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - pgsql
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: yarn run start:prod
        ports:
            - 4000:4000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - pgsql
    pgsql:
        image: postgres:alpine
        ports:
            - '5432:5432'
        container_name: 'pgsql'
        networks:
            - nesjs-network
        restart: always
        volumes:
            - pg-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: pb_dev

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    pg-data:

networks:
    nesjs-network:
